name: calculate-infra-cost

on:
  workflow_call:
    inputs:
      target_dirs:
        description: "Target TF directory that needs to be scanned for cost"
        required: true
        type: string
    secrets:
      infracost_api_key:
        description: "API Key of Infracost"
        required: true

env:
  # If you use private modules you'll need this env variable to use
  # the same ssh-agent socket value across all jobs & steps.
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  get-infra-cost:
    if: inputs.target_dirs != '[]'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET_DIRECTORY: "${{ fromJson(inputs.target_dirs) }}"
    name: Get infracost
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        # See https://github.com/infracost/actions/tree/master/setup for other inputs
        # If you can't use this action, see Docker images in https://infracost.io/cicd
        with:
          api-key: ${{ secrets.infracost_api_key }}

      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          path: master

      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=${{ matrix.TARGET_DIRECTORY }} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      # Checkout the current branch so we can create a diff.
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Debug
        run: |
          pwd
          ls

      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: |
          infracost diff --path=${{ matrix.TARGET_DIRECTORY }} \
                              --format=json \
                              --compare-to=/tmp/infracost-base.json \
                              --out-file=/tmp/infracost.json


      # Posts a comment to the PR using the 'update' behavior.
      # This creates a single comment and updates it. The "quietest" option.
      # The other valid behaviors are:
      #   delete-and-new - Delete previous comments and create a new one.
      #   hide-and-new - Minimize previous comments and create a new one.
      #   new - Create a new cost estimate comment on every push.
      # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
      - name: Post Infracost comment
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
        run: |
          infracost comment github --path=/tmp/infracost.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{github.token}} \
                                   --pull-request=${{github.event.pull_request.number}} \
                                   --behavior=update