name: calculate-infra-cost

on:
  workflow_call:
    inputs:
      target_dirs:
        description: "Target TF directory that needs to be scanned for cost"
        required: true
        type: string
    secrets:
      infracost_api_key:
        description: "API Key of Infracost"
        required: true

env:
  # If you use private modules you'll need this env variable to use
  # the same ssh-agent socket value across all jobs & steps.
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  get-infra-cost:
    if: inputs.target_dirs != '[]'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET_DIRECTORY: "${{ fromJson(inputs.target_dirs) }}"
    name: calculate cost
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.infracost_api_key }}

      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: master

      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=${{ matrix.TARGET_DIRECTORY }}     \
                              --format=json                             \
                              --out-file=/tmp/infracost-base.json

      # Checkout the current branch so we can create a diff.
      - name: Checkout current branch
        uses: actions/checkout@v3

      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: |
          infracost diff --path=${{ matrix.TARGET_DIRECTORY }}          \
                              --format=json                             \
                              --show-skipped                            \
                              --compare-to=/tmp/infracost-base.json     \
                              --out-file="/tmp/infracost-${{ matrix.TARGET_DIRECTORY }}.json"

      # Output Infracost of single Terraform module as DIFF
      - name: Show Infracost as Diff
        run: |
          infracost output --path "/tmp/infracost-${{ matrix.TARGET_DIRECTORY }}.json" --format diff --show-skipped

      # Upload all intermediate Terraform module JSONs so that they can be used across jobs.
      - uses: actions/upload-artifact@master
        with:
          name: "infracost"
          path: |
            # Upload all TF module cost JSONs
            #
            /tmp/*.json

            # Don't upload base JSON
            #
            !/tmp/infracost-base.json

  post-infra-cost:
    needs: [ get-infra-cost ]
    if: inputs.target_dirs != '[]' && github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: publish cost
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.infracost_api_key }}

      # Download intermediate Terraform module JSONs
      - uses: actions/download-artifact@master
        with:
          name: "infracost"
          path: "/tmp/"

      # Combine all intermediate module JSONs into one single JSON and print the combined output as DIFF
      - name: Show combined Infracost as Diff
        run: |
          # Combine all infracost-*.json files
          #
          infracost output --path "/tmp/infracost-*.json" --format json --show-skipped --out-file combined_infracost.json 

          # Show the combined InfraCost JSON in DIFF format
          #
          infracost output --path "combined_infracost.json" --format diff --show-skipped

      # Posts a comment to the PR using the 'update' behavior. This comment describes combined cost of all added/modified Terraform modules.
      - name: Post Infracost comment
        run: |
          infracost comment github --path=combined_infracost.json                         \
                                  --repo=$GITHUB_REPOSITORY                               \
                                  --github-token=${{github.token}}                        \
                                  --pull-request=${{github.event.pull_request.number}}    \
                                  --behavior=update