name: perform-security-scans

on:
  workflow_call:
    inputs:
      upload_sarif:
        description: "Flag to control if snyk scan issues need to be published in Github Security tab."
        required: false
        type: boolean
        default: true
      target_dirs:
        description: "List of all modified IaC directories (Terraform Modules, Helm Charts, etc.)"
        required: true
        type: string
      severity:
        description: "Severity threshold of alerts to report"
        required: false
        type: string
        default: "high"
      terrascan_iac_type:
        description: "IaC Type (helm, k8s, terraform)"
        required: false
        type: string
        default: "terraform"
      terrascan_iac_version:
        description: "IaC Version (helm: v3, k8s: v1, terraform: v12, v14, v15)"
        required: false
        type: string
        default: "v15"
    secrets:
      snyk_auth_token:
        description: "Auth Token for Snyk"
        required: true

env:
  UPLOAD_SARIF: ${{ inputs.upload_sarif }}
  SEVERITY: ${{ inputs.severity }}
  IAC_TYPE: ${{ inputs.terrascan_iac_type }}
  IAC_VERSION: ${{ inputs.terrascan_iac_version }}


jobs:
  snyk-scan:
    if: inputs.target_dirs != '[]'
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET_DIRECTORY: "${{ fromJson(inputs.target_dirs) }}"
    name: snyk
    steps:
      - name: Checkout application GitHub repo
        uses: actions/checkout@v3

      # The following step is needed because after PR merge, the GITHUB_REF that is required by Upload Sarif action does not meet its expected regex pattern. This steps make GITHUB_REF compatible with how Upload Sarif action is expecting it.
      - name: Update GITHUB_REF
        id: update-github-ref
        run: echo ::set-output name=fixed_github_ref::$([[ "$GITHUB_REF" =~ refs\/(heads|pull|tags)\/.* ]] && echo $GITHUB_REF || echo "refs/heads/$GITHUB_REF")
      
      - name: Run Snyk Scan
        # Snyk can be used to break the build when it detects security issues.
        # In this case we want to upload the issues to GitHub Code Scanning
        continue-on-error: true
        id: run_snyk
        uses: snyk/actions/iac@master
        env:
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://github.com/snyk/actions#getting-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.snyk_auth_token }}
        with:
          # Add the path to the configuration file that you would like to test.
          # For example `deployment.yaml` for a Kubernetes deployment manifest
          # or `main.tf` for a Terraform configuration file
          file: ${{ matrix.TARGET_DIRECTORY }}
          args: ${{ format('--severity-threshold={0}', env.SEVERITY) }}

      - name: Upload result to GitHub Code Scanning
        if: ${{ env.UPLOAD_SARIF == 'true' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
          ref: ${{ steps.update-github-ref.outputs.fixed_github_ref }}
          sha: ${{ github.sha }}

      - name: Check Snyk Scan Status
        if: steps.run_snyk.outcome == 'failure'
        run: |
          echo "SNYK SCAN FAILED: Check logs of 'Run Snyk Scan' step above!!!"
          exit 1

  terrascan:
    if: inputs.target_dirs != '[]'
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET_DIRECTORY: "${{ fromJson(inputs.target_dirs) }}"
    name: terrascan
    steps:
      - name: Checkout application GitHub repo
        uses: actions/checkout@v3

      # The following step is needed because after PR merge, the GITHUB_REF that is required by Upload Sarif action does not meet its expected regex pattern. This steps make GITHUB_REF compatible with how Upload Sarif action is expecting it.
      - name: Update GITHUB_REF
        id: update-github-ref
        run: echo ::set-output name=fixed_github_ref::$([[ "$GITHUB_REF" =~ refs\/(heads|pull|tags)\/.* ]] && echo $GITHUB_REF || echo "refs/heads/$GITHUB_REF")
      
      - name: Run Terrascan
        id: run_terrascan
        uses: tenable/terrascan-action@main
        continue-on-error: true
        with:
          iac_type: ${{ env.IAC_TYPE }}
          iac_version: ${{ env.IAC_VERSION }}
          iac_dir: ${{ matrix.TARGET_DIRECTORY }}
          policy_type: all
          sarif_upload: ${{ env.UPLOAD_SARIF }}

      - name: Upload result to GitHub Code Scanning
        if: ${{ env.UPLOAD_SARIF == 'true' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: terrascan.sarif
          ref: ${{ steps.update-github-ref.outputs.fixed_github_ref }}
          sha: ${{ github.sha }}

      - name: Check TerraScan Status
        if: steps.run_terrascan.outcome == 'failure'
        run: |
          echo "TERRASCAN FAILED: Check logs of 'Run Terrascan' step above!!!"
          exit 1